### ISSUE TITLE
Error: Couldn't change the robot type from Sota to CommU.

### ISSUE THREAD

**Issue by ayuguchi** [social-robotics-lab/RobotController_bin#1]
When I switched the robot type from "Sota" to "CommU" in System.properties, it didn't work and I faced the following error:

```
Exception in thread "pool-1-thread-2" java.lang.NoSuchMethodError: jp.vstone.RobotLib.CCommUMotion.LipSyncEnable(Z)V
        at servo.RobotSys.initCommU(RobotSys.java:80)
        at servo.RobotSys.getInstanceOfCRobotMotion(RobotSys.java:66)
        at servo.RobotSys.initialize(RobotSys.java:23)
        at utils.PoseExecutorThread.run(PoseExecutorThread.java:20)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ayuguchi** [comment]
The above error occurred around the lip motions of CommU.
https://github.com/social-robotics-lab/RobotController

**Comment by iiotakamasa** [comment]
The error happens because the library "sotalib.jar" is old.
You can find the new version of the library at `/home/vstone/lib` in CommU.
Please replace the old one to the new one in `RobotController/RobotController_lib`.
